sudo: false
language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run setup.py test
- coverage combine
after_success:
- codecov
before_deploy:
- git stash --all
deploy:
  provider: pypi
  user: JeongUkJae
  password:
    secure: kLDMob2GA5smTe3nfIplqwZ0aN2jPGhUJNJ/8pwu5sLbAmoMgJ+JRHUCFBj9AdV6rQys6Ikb/AWsSLBXeELglqigX/AfhSc4FMyoNHk9xEvdGbIyOSuR97viCQIaNjf/4/vpmDyTTNdnxkOF9qIIEdFqoZAKnXZHDZon4f8pOxbIoZ1t+2WDY8kWxjphrWt9ULQAO2y+/E2iGRikL2ftbnkOaXtvJwrUwk7e9KuBfoVcSBKUUy52PPkiR6PCDCf08Pz42F+2ekZrlltmyg1sKHocjbaDwFarMfntpkdlEXr3pJJXT3lfLqtZHYHbauzLRnCg0hPjeOKyS9m6m0TqU5KwslBA2f041Con4E6MCOSsn+shdx8aHaBCBsDzEYJk9QqwL+e+RsJtj5gHEHItSJq9EI9XWBqE/J2OGWk7hRESKCwzBJHSW36cTMWVqQ8fWAnizzNgEiIvTVYk5z+fJE6hbgvuIjYvGMH2yIrcQnql1RpQsmvjcFCaTjg57HOwbvekSn5HsBOabnUcuIIWCassNYWilHI7hutX9xf0M40e0N/0+N7+y0Jo3s/JU2PpsdmVKReEpoG+xZBknNsvMbr3ky/d4ROmF3NSnKgLMAy6G4bzT/ipE3Zw6dzBmjbn6A8W3nS6hUsk+D7K7p9ouJ+jz8dnmON1JiStSqcmYos=
  on:
    branch: release
