sudo: false
language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - coverage run setup.py test
  - coverage combine
after_success:
  - codecov
before_deploy:
  - git stash --all
deploy:
  provider: pypi
  user: JeongUkJae
  password:
    secure: "GLY/OCyN6ZssY+UxZh4lLTzARk+KqNgPYNqxplLL3Jsf/DRsh4aTLTsWu6srJyjIv3C7IksuLwbiXA9uKrilL2n8CEZ0OdnmvVNmGkvIWyXA5GjSMlWA1NpsurkrtkyknLb78KD+5OrOEQMpikBoszTcuNpFTVhSRr1po2r+p2zLn4DOASgIH3GcFN+6MY76zQyKZ7oGLrwovazkXTvb22XbLPNl3QkTvyQ2ae9v/zoY1x3MEJLTMgJlacV6bZvQSxe4rKkautYNOivU6fq1+80IADQOEFBYDz9CaIHEk0cz1ddLUijdSv7+y975zlTr9Ko3+ywGDUR1Vda9mwyzEkVgGJ5LDsS1gG7zJLdvJ/4lRPh75Kj7RHsPB8l6Lrg77XyJXbOLcAmfHrn9olDC9qeNJHZh2Q2xwZXEDIHbuYMGHTk5m5sFuMeHrTNoE6ETbu2KyXxT3ZpHu2vbxTpRembzZgF8/CJPP1qa0vBHCDXpTvpgT1T+KbJwUSBR6RD+12N8jqdR2iO1/eNMxA3mlPABxB2wJhuo00yMUlpqafRmLKVcjhqQQYe8x7v0hbXmIlgdchA/d2q5ZB3QK5UfdIeJ2l9KO7i+Yjkh7qK9gR8fmvPDiDS8UELucPeDEnqVtoZPQIiepHzfoEa+seBCveEsGwAoWeCT7Qd870MMxLo="
  on:
    branch: release
