sudo: false
language: python
python:
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
- pip install codecov
script:
- coverage run setup.py test
- coverage combine
after_success:
- codecov
before_deploy:
- git stash --all
deploy:
  provider: pypi
  user: JeongUkJae
  password:
    secure: TuqAiKF6Wa9q7X0vqeck5u5kq+24LbfAbi87POLw7BP6S8V0rqpysPzPtpr3D3O6gYH8EskpJ4ilQ7Vj/PVRHDdxk4go+CWhToIxbKOoANOZK8stTLexV431Wye8Iwm0AerkDTlPxYwyI4ZcQdwad0hMZ1bH7BnedP8veCKkSgArz0TemDSCGt9BI7KEvBgEu8oy1SN2mNLbbzz89T2DeyJcNP6LizfNLxtQnUzSvCfdQ2mcbfED929UEAdWHqwvNHBbMWcSWATyYukgfDPszlym4x0hRgEFBLPsFE/lZr2q2D+3iO5thfX5S0iSJ6dYEHWACSFcukH7yM7xiChFvmCbPiZqmzl+/a05Bl8c0ohjB6xS81hkPJtsMR/KVPuDwG4WY//E4KXHxxjwiwcJygBGr04dYWk7Zi63MZ+y4Pwtl9zrnrtonGbD9pBRck+wX58rpFDH7Xp5LSACfCuPG09o7Mybtqmq4SOvvfv72q7JC6VfWYAwH3apiQrAZ3fcpeP78FZlujsm6nzC/hK/5jDXNRAspZb67oR0t8Gtc8IVOjetW9tm/GMaKCKSP2Qy6HpbmCu1K6JTMzKtOjzuEi+Xod6ahHdT9LX4NzoYloyA0RZBekCzw71Er+m13UQ1/L2wDWR+gayQRXtEOkGwlPcB9rWZFJYILHWqigYdT+U=
  on:
    tags: true
    branch: release
