sudo: required
language: python
python:
  - '3.6'
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install:
  - pip install selenium
  - pip install codecov
script:
  - coverage run --source=pytistory setup.py test
after_success:
  - codecov
